services:
    web:
        build:
            context: ./web
            dockerfile: Dockerfile
        ports:
            - "3000:3000" # Map container port to the host
        volumes:
            - ./web:/app # Mount web directory to container
        env_file:
            - ./web/.env # Load environment variables from web .env file
        depends_on:
            - server

    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "8000:8000" # Map container port to the host
        volumes:
            - ./server:/app # Mount server directory to container
        env_file:
            - ./server/.env # Load environment variables from server .env file
