services:
    web:
        build:
            context: ./web
            dockerfile: Dockerfile
        ports:
            - "3000:3000" # Map container port to the host
        volumes:
            - .:/usr/src/app # Mount local directory to the container
    #   env_file:
    #     - .env # Load environment variables from the .env file

    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "8000:8000" # Map container port to the host
        volumes:
            - .:/usr/src/app # Mount local directory to the container
#   env_file:
#     - .env # Load environment variables from the .env file
