version: "3.8"
services:
    database:
        container_name: postgresql
        image: postgres
        restart: always
      
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: api
        ports:
            - "5442:5432"